// <auto-generated />
using System;
using DesktopPro.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesktopPro.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912101453_IsolatedVaultArchitecture")]
    partial class IsolatedVaultArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesktopPro.Domain.Entities.AiTriageSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuggestedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("SuggestedWorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuggestedWorkspaceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("AiTriageSuggestions");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.FileWorkspaceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkspaceGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.HasIndex("WorkspaceGroupId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("FileWorkspaceLinks");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.VirtualFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMissing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LlmSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("VaultRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("VirtualFiles");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsTemporal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.WorkspaceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceGroups");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.AiTriageSuggestion", b =>
                {
                    b.HasOne("DesktopPro.Domain.Entities.VirtualFile", "VirtualFile")
                        .WithMany()
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualFile");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.FileWorkspaceLink", b =>
                {
                    b.HasOne("DesktopPro.Domain.Entities.VirtualFile", "VirtualFile")
                        .WithMany("WorkspaceLinks")
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopPro.Domain.Entities.WorkspaceGroup", "WorkspaceGroup")
                        .WithMany("FileLinks")
                        .HasForeignKey("WorkspaceGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DesktopPro.Domain.Entities.Workspace", "Workspace")
                        .WithMany("FileLinks")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VirtualFile");

                    b.Navigation("Workspace");

                    b.Navigation("WorkspaceGroup");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.VirtualFile", b =>
                {
                    b.HasOne("DesktopPro.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("DesktopPro.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.WorkspaceGroup", b =>
                {
                    b.HasOne("DesktopPro.Domain.Entities.WorkspaceGroup", "ParentGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DesktopPro.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceGroups")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.VirtualFile", b =>
                {
                    b.Navigation("WorkspaceLinks");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("FileLinks");

                    b.Navigation("WorkspaceGroups");
                });

            modelBuilder.Entity("DesktopPro.Domain.Entities.WorkspaceGroup", b =>
                {
                    b.Navigation("FileLinks");

                    b.Navigation("SubGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
