<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\DesktopPro.Application\DesktopPro.Application.csproj" />
    <ProjectReference Include="..\..\Core\DesktopPro.Domain\DesktopPro.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Contexts\" />
    <Folder Include="Design\" />
    <Folder Include="Interceptors\" />
    <Folder Include="Migrations\" />
    <Folder Include="Repositories\" />
    <Folder Include="Seeders\" />
  </ItemGroup>

</Project>
