<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BackgroundJobs\**" />
    <Compile Remove="Configurations\**" />
    <Compile Remove="Identity\**" />
    <Compile Remove="Logging\**" />
    <Compile Remove="Notifications\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="Storage\**" />
    <EmbeddedResource Remove="BackgroundJobs\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <EmbeddedResource Remove="Identity\**" />
    <EmbeddedResource Remove="Logging\**" />
    <EmbeddedResource Remove="Notifications\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="Storage\**" />
    <None Remove="BackgroundJobs\**" />
    <None Remove="Configurations\**" />
    <None Remove="Identity\**" />
    <None Remove="Logging\**" />
    <None Remove="Notifications\**" />
    <None Remove="Services\**" />
    <None Remove="Storage\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\DesktopPro.Application\DesktopPro.Application.csproj" />
    <ProjectReference Include="..\..\Core\DesktopPro.Domain\DesktopPro.Domain.csproj" />
  </ItemGroup>

</Project>
